const BOOK_ALIASES: Array<[string, string]> = [
  ["GENESIS", "GEN"],
  ["GEN", "GEN"],
  ["EXODUS", "EXO"],
  ["EXOD", "EXO"],
  ["EXO", "EXO"],
  ["LEVITICUS", "LEV"],
  ["LEV", "LEV"],
  ["NUMBERS", "NUM"],
  ["NUM", "NUM"],
  ["DEUTERONOMY", "DEU"],
  ["DEUT", "DEU"],
  ["DEU", "DEU"],
  ["JOSHUA", "JOS"],
  ["JOSH", "JOS"],
  ["JOS", "JOS"],
  ["JUDGES", "JDG"],
  ["JUDG", "JDG"],
  ["JDG", "JDG"],
  ["RUTH", "RUT"],
  ["RUT", "RUT"],
  ["1 SAMUEL", "1SA"],
  ["1SAMUEL", "1SA"],
  ["1 SAM", "1SA"],
  ["1SAM", "1SA"],
  ["I SAMUEL", "1SA"],
  ["2 SAMUEL", "2SA"],
  ["2SAMUEL", "2SA"],
  ["2 SAM", "2SA"],
  ["2SAM", "2SA"],
  ["II SAMUEL", "2SA"],
  ["1 KINGS", "1KI"],
  ["1KINGS", "1KI"],
  ["1 KGS", "1KI"],
  ["1KGS", "1KI"],
  ["I KINGS", "1KI"],
  ["2 KINGS", "2KI"],
  ["2KINGS", "2KI"],
  ["2 KGS", "2KI"],
  ["2KGS", "2KI"],
  ["II KINGS", "2KI"],
  ["1 CHRONICLES", "1CH"],
  ["1CHRONICLES", "1CH"],
  ["1 CHR", "1CH"],
  ["1CHR", "1CH"],
  ["I CHRONICLES", "1CH"],
  ["2 CHRONICLES", "2CH"],
  ["2CHRONICLES", "2CH"],
  ["2 CHR", "2CH"],
  ["2CHR", "2CH"],
  ["II CHRONICLES", "2CH"],
  ["EZRA", "EZR"],
  ["EZR", "EZR"],
  ["NEHEMIAH", "NEH"],
  ["NEH", "NEH"],
  ["ESTHER", "EST"],
  ["EST", "EST"],
  ["JOB", "JOB"],
  ["PSALM", "PSA"],
  ["PSALMS", "PSA"],
  ["PS", "PSA"],
  ["PSA", "PSA"],
  ["PROVERBS", "PRO"],
  ["PROV", "PRO"],
  ["PRO", "PRO"],
  ["ECCLESIASTES", "ECC"],
  ["ECC", "ECC"],
  ["SONG OF SOLOMON", "SNG"],
  ["SONG OF SONGS", "SNG"],
  ["SONG", "SNG"],
  ["SNG", "SNG"],
  ["ISAIAH", "ISA"],
  ["ISA", "ISA"],
  ["JEREMIAH", "JER"],
  ["JER", "JER"],
  ["LAMENTATIONS", "LAM"],
  ["LAM", "LAM"],
  ["EZEKIEL", "EZK"],
  ["EZEK", "EZK"],
  ["EZK", "EZK"],
  ["DANIEL", "DAN"],
  ["DAN", "DAN"],
  ["HOSEA", "HOS"],
  ["HOS", "HOS"],
  ["JOEL", "JOL"],
  ["JOL", "JOL"],
  ["AMOS", "AMO"],
  ["AMO", "AMO"],
  ["OBADIAH", "OBA"],
  ["OBAD", "OBA"],
  ["OBA", "OBA"],
  ["JONAH", "JON"],
  ["JON", "JON"],
  ["MICAH", "MIC"],
  ["MIC", "MIC"],
  ["NAHUM", "NAM"],
  ["NAH", "NAM"],
  ["NAM", "NAM"],
  ["HABAKKUK", "HAB"],
  ["HAB", "HAB"],
  ["ZEPHANIAH", "ZEP"],
  ["ZEPH", "ZEP"],
  ["ZEP", "ZEP"],
  ["HAGGAI", "HAG"],
  ["HAG", "HAG"],
  ["ZECHARIAH", "ZEC"],
  ["ZECH", "ZEC"],
  ["ZEC", "ZEC"],
  ["MALACHI", "MAL"],
  ["MAL", "MAL"],
  ["MATTHEW", "MAT"],
  ["MATT", "MAT"],
  ["MAT", "MAT"],
  ["MARK", "MRK"],
  ["MRK", "MRK"],
  ["LUKE", "LUK"],
  ["LUK", "LUK"],
  ["JOHN", "JHN"],
  ["JHN", "JHN"],
  ["ACTS", "ACT"],
  ["ACT", "ACT"],
  ["ROMANS", "ROM"],
  ["ROM", "ROM"],
  ["1 CORINTHIANS", "1CO"],
  ["1CORINTHIANS", "1CO"],
  ["1 COR", "1CO"],
  ["1COR", "1CO"],
  ["I CORINTHIANS", "1CO"],
  ["2 CORINTHIANS", "2CO"],
  ["2CORINTHIANS", "2CO"],
  ["2 COR", "2CO"],
  ["2COR", "2CO"],
  ["II CORINTHIANS", "2CO"],
  ["GALATIANS", "GAL"],
  ["GAL", "GAL"],
  ["EPHESIANS", "EPH"],
  ["EPH", "EPH"],
  ["PHILIPPIANS", "PHP"],
  ["PHIL", "PHP"],
  ["PHP", "PHP"],
  ["COLOSSIANS", "COL"],
  ["COL", "COL"],
  ["1 THESSALONIANS", "1TH"],
  ["1THESSALONIANS", "1TH"],
  ["1 THESS", "1TH"],
  ["1THESS", "1TH"],
  ["I THESSALONIANS", "1TH"],
  ["2 THESSALONIANS", "2TH"],
  ["2THESSALONIANS", "2TH"],
  ["2 THESS", "2TH"],
  ["2THESS", "2TH"],
  ["II THESSALONIANS", "2TH"],
  ["1 TIMOTHY", "1TI"],
  ["1TIMOTHY", "1TI"],
  ["1 TIM", "1TI"],
  ["1TIM", "1TI"],
  ["I TIMOTHY", "1TI"],
  ["2 TIMOTHY", "2TI"],
  ["2TIMOTHY", "2TI"],
  ["2 TIM", "2TI"],
  ["2TIM", "2TI"],
  ["II TIMOTHY", "2TI"],
  ["TITUS", "TIT"],
  ["TIT", "TIT"],
  ["PHILEMON", "PHM"],
  ["PHLM", "PHM"],
  ["PHM", "PHM"],
  ["HEBREWS", "HEB"],
  ["HEB", "HEB"],
  ["JAMES", "JAS"],
  ["JAS", "JAS"],
  ["1 PETER", "1PE"],
  ["1PETER", "1PE"],
  ["1 PET", "1PE"],
  ["1PET", "1PE"],
  ["I PETER", "1PE"],
  ["2 PETER", "2PE"],
  ["2PETER", "2PE"],
  ["2 PET", "2PE"],
  ["2PET", "2PE"],
  ["II PETER", "2PE"],
  ["1 JOHN", "1JN"],
  ["1JOHN", "1JN"],
  ["1 JN", "1JN"],
  ["1JN", "1JN"],
  ["I JOHN", "1JN"],
  ["2 JOHN", "2JN"],
  ["2JOHN", "2JN"],
  ["2 JN", "2JN"],
  ["2JN", "2JN"],
  ["II JOHN", "2JN"],
  ["3 JOHN", "3JN"],
  ["3JOHN", "3JN"],
  ["3 JN", "3JN"],
  ["3JN", "3JN"],
  ["III JOHN", "3JN"],
  ["JUDE", "JUD"],
  ["JUD", "JUD"],
  ["REVELATION", "REV"],
  ["REVELATIONS", "REV"],
  ["REV", "REV"],
];

const BOOK_CODE_MAP = new Map<string, string>(BOOK_ALIASES);

const USFM_REFERENCE = /^[1-3]?[A-Z]{2,4}\.\d+(\.\d+(?:-\d+)?)?$/;

function normalizeBookName(book: string): string {
  return book
    .trim()
    .replace(/\./g, "")
    .replace(/\s+/g, " ")
    .toUpperCase();
}

/**
 * Accepts either USFM (`JHN.3.16`) or human-readable (`John 3:16`) references.
 * Returns normalized USFM format when possible; otherwise returns the original trimmed input.
 */
export function normalizeBibleReference(input: string): string {
  const raw = input.trim();
  if (!raw) return raw;

  const compact = raw.replace(/\s+/g, "").toUpperCase();
  if (USFM_REFERENCE.test(compact)) return compact;

  const match = raw
    .replace(/[\u2013\u2014]/g, "-")
    .match(/^(.+?)\s+(\d+)(?::(\d+)(?:-(\d+))?)?$/);

  if (!match) return raw;

  const [, bookRaw, chapter, verseStart, verseEnd] = match;
  const bookCode = BOOK_CODE_MAP.get(normalizeBookName(bookRaw));
  if (!bookCode) return raw;

  if (!verseStart) return `${bookCode}.${chapter}`;
  if (!verseEnd) return `${bookCode}.${chapter}.${verseStart}`;
  return `${bookCode}.${chapter}.${verseStart}-${verseEnd}`;
}
